import requests

bing_cookies = [
    {
        "domain": ".bing.com",
        "expirationDate": 1741352219.171303,
        "hostOnly": False,
        "httpOnly": False,
        "name": "MUID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "35542A950E9E6F2017F33E9E0F086E23"
    },
    {
        "domain": "www.bing.com",
        "expirationDate": 1741873837.868904,
        "hostOnly": True,
        "httpOnly": True,
        "name": "MUIDB",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "35542A950E9E6F2017F33E9E0F086E23"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1740204426.592883,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SRCHD",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "AF=NOFORM"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1740204426.593064,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SRCHUID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "V=2&GUID=1305130F58A14496AE8BB5E32440D387&dmnchg=1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1723189497.765911,
        "hostOnly": False,
        "httpOnly": False,
        "name": "ANON",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "A=698971E9C469AE65B02E39DDFFFFFFFF&E=1d54&W=1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1724769896.765986,
        "hostOnly": False,
        "httpOnly": False,
        "name": "NAP",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "V=1.9&E=1cfa&C=u1ihyMwK-PF9dfWAEbhzI-IPSmU8iiPeFNRjamZPy-jfJES8Lhng7Q&W=1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742024697.766063,
        "hostOnly": False,
        "httpOnly": False,
        "name": "PPLState",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1740748476.750326,
        "hostOnly": False,
        "httpOnly": False,
        "name": "MMCASM",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "ID=DBBF5A96077949A1ABB0B2B57C49BEE9"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742403323.533041,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_UR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "QS=0&TQS=0"
    },
    {
        "domain": "www.bing.com",
        "expirationDate": 1739000706.69345,
        "hostOnly": True,
        "httpOnly": False,
        "name": "MicrosoftApplicationsTelemetryDeviceId",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "74d73cef-3110-4d90-b38d-c396bf3abd41"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742024697.766112,
        "hostOnly": False,
        "httpOnly": True,
        "name": "KievRPSSecAuth",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "FACCBBRaTOJILtFsMkpLVWSG6AN6C/svRwNmAAAEgAAACNHVdF9l6croQAQsxZi9UBj1O2J1UO49oYpF2cRJVjx4Yjf/d+/tYTqA+tt1Cv2SSSMynJSJy3CHwuMnO8Pdoa+1LnK5UjEZpTz1wBkwqqses6UTfWPGTETSxUdMHFSPncxPxNIWVYd3CYjFVstEDApESe9WDpJ3Tcf/pzVivoiq2iaF+afFOC+S+sIWiYDYQizYBwLULz5FyenV2A/q+plfHJvLgVWvlM4eH0YGP4ksRI+klQcjIS3F17DlaEWdWHng1HACaGrA8ZC2yeL8dxL7dltXWLoIhmELlnGGdL7Uo/nPXK3dNnSXruA7mKqcFdkLt3POlngMWPxtInGxPArbOhOmyFXvwAVRHbqbaRsCJvpXOQaVGLpmDPCllImI24cNpu5ld1yfrs3UmC2sZyOJsq25aMm724LXLS4IA6sYTDHj5+M2RBnseS1mbKB4YvmSj17MwYWnqEkHLr0HxmkEQ42DytM3u3Q7jViVmulRLajwI84BCqh/ervlJiYozRb7bJHMVCaKj/7OBEUAtpFDyL+7HecQR/0xrdhl9nM2U+k2SvbpTLqlxsXCLWnPIXJ64b/hmEvr9TTr/v7qsPgJ0mmT4OSrY8LFsuQx5DlBxz1iT9BtpTS4SlAPABAxsB/qFAjBR1kFucHSvHSheTnuR7h6eAZO97BiqLmTNLj6IPAWE+DMJU301DNBEF9f3+Ijgspfb2ls124nA0Z7l72CPwA9HrnlhiLL+PPEZen4fPVnNgy+X2p0jGH+hcCZn8TebVytVz9s6DFjpTiX38fslMa8BFIN8goi7OZaO1w9geaCsnfUqvso50SqzJgyrpYLYakm6E3tKRlfmVvIW2rbeTEfluMHzFMqB9jJChJxZ739A2PTwwmWDOm1R0lYM3ls5BSmx7xpmcCzOvh8E+Y8XiYK11AtPV56GXB8TKrfyIgzvXssz7cJN3PpTK2CUlQ37E0PiFq+dkKikp5MydN8602/N/Qrn6UVnOHdPa5TugJFF7vF/UHveVxYywyPWyfkgRHA8n5BlHhpgJakSN4vnlrjaiGxmIQ56U/fSRNEwPdVvpJiXtjB82GdzvLvNzFPBO5DnTO5HtObeadzoLdV2M4ZkydB5kSi6+y3UV5Rii62/0Alb5JqRC063WBjEsGpz4ii7SdLKYPOV6z9DvgbZ1v/eUPI7Ij2UqqKBg6qxnAgFB7AOnFXIbAYP676+Wx3zThXts58PyU/+7Rt7xERqqVZIIAvNfeymRkwgXq+cuEaFPRP0bczBBQHKZ5YSmjhwa3ZOPrYB4KyqXwP69izhaa2WbP31o8sAP4kijvnv+ycYqfl/kMEUMZqeV2fS4+GL85Nyg5yBu7NQ1laIKBSmRdsUi/ITB+IGcMg8t7U/yU/jxU/+JJEqQMKMqia23Ow4Df7UfL/EpRfPkR4kKGs+F3dSLbi4josbAzG+kWcDkbOBvzYN4SeXxQAos4gvbvE8R93G3qF/f4CUYtB5R0="
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1708674297.766171,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_U",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "1_C-5mWtjF5PPSF9XQbCuVK4P9y4YxhQgjpANA0tAIDcjFGYIoiWUDODQ5bmqzsgqEhc3Lpm_GrSDjkjiZPFAtrXDnG8_SYMtoLAS5ZRQ_25k99WJ-ziCC2ATzImQahLq0NxOQ2EJUhh6uZ4AgZw2Ii0sGQp2ilNMp5AgQAvwOYV-UBO7u_A-GmVOZMGfDQCWcDbFLlNkJkwm_kJd_b3nqKFlTwZfO3-bG1SlMw4vIeQ"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1708674297.703433,
        "hostOnly": False,
        "httpOnly": True,
        "name": "WLID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "q/P5vR4scX1Kb5kfuxr3pCJRq/higNQ98GlnDYXBXsM25R3gubyRAaDHDtvieK3DvqTR52ic/NNJqPyrLwIdGAR6XkdDIbXz81oLohvatdU="
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742403323.533587,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_HPVN",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "CS=eyJQbiI6eyJDbiI6NSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiUCJ9LCJTYyI6eyJDbiI6NSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiSCJ9LCJReiI6eyJDbiI6NSwiU3QiOjAsIlFzIjowLCJQcm9kIjoiVCJ9LCJBcCI6dHJ1ZSwiTXV0ZSI6dHJ1ZSwiTGFkIjoiMjAyNC0wMi0xM1QwMDowMDowMFoiLCJJb3RkIjowLCJHd2IiOjAsIlRucyI6MCwiRGZ0IjpudWxsLCJNdnMiOjAsIkZsdCI6MCwiSW1wIjo3LCJUb2JuIjowfQ=="
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739465944,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_clck",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "1zb6gq%7C2%7Cfj9%7C1%7C1484"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "WLS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "C=58b6c012a70fb6c7&N=Gerison"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": True,
        "name": "_Rwho",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "u=d"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "_SS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "SID=0E24C41D6A2B629305B9D0356BBD638A&R=1018&RB=1018&GB=0&RG=1000&RP=1018"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": True,
        "name": "_EDGE_S",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": True,
        "storeId": "0",
        "value": "SID=0E24C41D6A2B629305B9D0356BBD638A&mkt=sw-ke&ui=en-us"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742732839.702904,
        "hostOnly": False,
        "httpOnly": True,
        "name": "USRLOC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "HS=1&ELOC=LAT=-1.283329963684082|LON=36.81666946411133|N=Nairobi%2C%20Nairobi%20County|ELT=1|"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1739800226.982449,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_RwBf",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "r=0&ilt=1&ihpd=0&ispd=1&rc=1018&rb=1018&gb=0&rg=1000&pc=1018&mtu=0&rbb=0.0&g=0&cid=&clo=0&v=2&l=2024-02-17T08:00:00.0000000Z&lft=0001-01-01T00:00:00.0000000&aof=0&ard=0001-01-01T00:00:00.0000000&rwdbt=2023-12-04T00:51:17.8186526-08:00&o=0&p=BINGCOPILOTWAITLIST&c=True&t=3673&s=2023-03-27T06:41:37.9588734+00:00&ts=2024-02-17T13:50:27.3533378+00:00&rwred=0&wls=2&wlb=0&wle=0&ccp=0&lka=0&lkt=0&aad=0&TH=&mta=0&e=_mB2RezcDJoQMCuiu2EuzDd4D8ioTp_tGASxDqbzHZXfzj_ZeySgwcaw2VoxwIxh1TIhJTVIusfAh57AEs7a5g&A=&rwflt=2023-12-29T04:21:48.1468242-08:00"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742737835.730645,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SRCHUSR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "DOB=20240119&T=1708177823000&TPC=1708177835000&POEX=W"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "dsc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "order=News"
    },
    {
        "domain": ".bing.com",
        "expirationDate": 1742737838.105808,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SRCHHPGUSR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "SRCHLANG=en&IG=27CD56106C53462AB5896958B53FACCF&PV=15.0.0&BRW=W&BRH=S&CW=1366&CH=633&SCW=1366&SCH=112&DPR=1.0&UTC=180&DM=1&CIBV=1.1573.4&HV=1708177836&WTS=63843061492&PRVCW=1366&PRVCH=633"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": True,
        "name": "_C_ETH",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "1"
    },
    {
        "domain": ".bing.com",
        "hostOnly": False,
        "httpOnly": False,
        "name": "ipv6",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "hit=1708181436947&t=4"
    }
]

gemini_cookies = [
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.605353,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "g.a000fwjpVrh7-TVe-iwqgp9FQOvOgr50TqdjZl-RAC5LE-0zKQ0I7_cpIeYEcNo35-N0WXiM-gACgYKAfkSAQASFQHGX2MihlOtZs3ULLYbD8ZXSY_cfhoVAUF8yKp2ES97kv4fvhtDlneC6WLY0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.605498,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "g.a000fwjpVrh7-TVe-iwqgp9FQOvOgr50TqdjZl-RAC5LE-0zKQ0IIQiEzxfivtX7nUNGFGXV8AACgYKAWgSAQASFQHGX2MiJ4bQqz3SyFH6UiK-T4wAiRoVAUF8yKplLZN93Wkfdgg4gmixJOm00076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.60563,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "g.a000fwjpVrh7-TVe-iwqgp9FQOvOgr50TqdjZl-RAC5LE-0zKQ0ITxYsKnAac-ERiDpi1DFs7QACgYKAbASAQASFQHGX2MiX-yOJpYXCSgNiD_YJe70CRoVAUF8yKqtG6MCfrnIQZZbGoMNh3AL0076"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.606083,
        "hostOnly": False,
        "httpOnly": True,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "A8eP2qFnQl1udAGCa"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.6062,
        "hostOnly": False,
        "httpOnly": True,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "ASLTH0zQeHg6pB_CH"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.606313,
        "hostOnly": False,
        "httpOnly": False,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "-RMWczo2ULlk7-ac/AjcOpR0z_B8SSzp-b"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.606429,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "LxCiZ_fz9Lk2f_a3/AwuRWfTMKLpx26QmE"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.606543,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "LxCiZ_fz9Lk2f_a3/AwuRWfTMKLpx26QmE"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1741016664.606667,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "LxCiZ_fz9Lk2f_a3/AwuRWfTMKLpx26QmE"
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1742807004.041037,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GA1.1.802592463.1707454869"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1723525139.324766,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "CgQIuJoB"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1721194452.003518,
        "hostOnly": False,
        "httpOnly": True,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "Ae3NU9P9bQZOZx2pJJpkdwM_a7JaBZ1b1vl_P2UJMk1j5FW4VZehwfOq9A"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1724054203.593282,
        "hostOnly": False,
        "httpOnly": True,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "511=Mw6yutZVLor8X7PrnwH0rA2t-2HOAo6Zo7fpkLhmXLn1GLwOFGBw_NRS_F-T6WBz4nVUUqnj2Ekt2hqAyGWyFD6lk9gqFG4nrFlch8_u48J0mR6Gp2g2AAtAL2fGQBp0wMJKrSoGjTNWLHwf7gXUKemjyVGqcpczNAhHEfunVquFuPuxZ77M0UYVTZ49-8WkNMu1DGeuab6uum0zYinRqA35waIPN-io61A-ZM2HRe9I44CNHW27sD9JIA9kGxO02hx7JzgLb43S5vgGruCgsQPyWDSgf_Uz6XpTIEW46IN5NtRk2BYcOw02etQnTLS_i4nYbO6DeJ4kmPgPmYPhAtvN7z4Z9-U"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1710835458.726042,
        "hostOnly": False,
        "httpOnly": False,
        "name": "1P_JAR",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "2024-02-18-08"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1739782973.074783,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "sidts-CjIBYfD7ZyIhZJkERRwjsFE0x1nDIhAO8Lx1xTBuvYwwNO4e_R-7EyABNtNBVAKWoo0V9BAA"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1739782973.07494,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "sidts-CjIBYfD7ZyIhZJkERRwjsFE0x1nDIhAO8Lx1xTBuvYwwNO4e_R-7EyABNtNBVAKWoo0V9BAA"
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1742807004.05502,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ga_WC57KJ50ZZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GS1.1.1708247004.15.0.1708247004.0.0.0"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1739783005.279399,
        "hostOnly": False,
        "httpOnly": False,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "ABTWhQGsDi0h_KBUkYHKPVKS5FKoSQyiUoYbACi0VxcYVS4PT9_ATBt82e5S39xahrq2aAirbg"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1739783005.279653,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "ABTWhQHDHWL8xeGGTXJoW-Gz2EufbAjZBgvYw_EPCtDKaeQPSDMG3XtooeJIwDLbk99b7TWimaY"
    },
    {
        "domain": ".google.com",
        "expirationDate": 1739783005.279839,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "ABTWhQFRAaSoXPKDWG_42xBSQV4buRAvR4ts-k7LgQencJzi7bYNPAoy4TjYx2yk1PDw68Xb6Q"
    }
]

BASE = "http://127.0.0.1:5000"

# bing_response = requests.post(BASE + "/ask/bing_web", json={
#     "question": "Latest nextjs version?",
#     "cookies": bing_cookies
# })
#
gemini_response = requests.post(BASE + "/ask/gemini_web", json={
    "question": "Latest nextjs version?",
    "cookies": gemini_cookies
})

# gemini_api_response = requests.post(BASE + "/ask/gemini_api", json={
#     "question": "Latest nextjs version?"
# })

models_response = requests.get(BASE+'/supported_models')
print(gemini_response.json())
